services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # or
    # environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      # - OPENAI_API_KEY=your_openai_api_key
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
    image: "nheek/codify-backend:latest"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3063:5173"
    image: "nheek/codify-frontend:latest"